//
//  ProtocolErrorEvent.swift
//  Wibmo3ds
//
//  Created by neeraj goyal on 15/02/18.
//

import Foundation

/// A protocol error is any error message that is returned by the ACS or
/// an error message that is generated by the 3DS SDK to be returned to the ACS

@objc public class ProtocolErrorEvent : NSObject {
    
    @objc public var sdkTransactionID: String
    @objc public var errorMessage: ErrorMessage
    
    /// The ProtocolErrorEvent constructor shall create an object with the specified inputs
    /// - Parameters:
    ///     - sdkTransactionID: SDK Transaction ID
    ///     - errorMessage: Error message
    @objc public init(_ sdkTransactionID: String, _ errorMessage: ErrorMessage) {
        self.sdkTransactionID = sdkTransactionID
        self.errorMessage = errorMessage
    }
    
    /// Returns the error message
    @objc public func getErrorMessage() -> String {
        return errorMessage.getErrorDescription()
    }
    
    /// Returns the SDK Transaction ID
    @objc public func getSDKTransactionID() -> String {
        return sdkTransactionID
    }
}
